const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
test('安卓 MVP 工程包含入口、清单和本地持久化逻辑', () => {
  assert.ok(fs.existsSync('android-mvp/app/src/main/java/com/bianqujian/app/MainActivity.kt'));
  const code = fs.readFileSync('android-mvp/app/src/main/java/com/bianqujian/app/MainActivity.kt', 'utf8');
  assert.match(code, /ACTION_PICK/);
  assert.match(code, /MediaStore\.Images\.Media/);
  assert.match(code, /getSharedPreferences/);
  assert.match(code, /codePattern/);
  assert.match(code, /FLAG_DEBUGGABLE/);
  assert.match(code, /completedList/);
  assert.match(code, /IN_TRANSIT/);
  assert.match(code, /READY/);
  assert.match(code, /PICKED_UP/);
  assert.match(code, /CANCELLED/);
  assert.match(code, /运输中/);
  assert.match(code, /待取件/);
  assert.match(code, /已取件/);
  assert.match(code, /已取消/);
  assert.match(code, /选择包裹状态/);
  assert.match(code, /打开拼多多扫描取件/);
  assert.match(code, /getLaunchIntentForPackage\("com\.xunmeng\.pinduoduo"\)/);
  assert.doesNotMatch(code, /是否跳转到拼多多/);
  assert.match(code, /if \(packageManager\.getLaunchIntentForPackage\("com\.xunmeng\.pinduoduo"\) == null\)/);
  assert.match(code, /market:\/\/search\?q=拼多多/);
  assert.match(code, /sj\.qq\.com\/app\/search\?key=拼多多/);
  const wrapper = fs.readFileSync('android-mvp/gradle/wrapper/gradle-wrapper.properties', 'utf8');
  assert.match(wrapper, /gradle-9\.3\.0-bin\.zip/);
  const manifest = fs.readFileSync('android-mvp/app/src/main/AndroidManifest.xml', 'utf8');
  assert.match(manifest, /BIND_NOTIFICATION_LISTENER_SERVICE/);
  assert.match(manifest, /<queries>/);
  assert.match(manifest, /android:name="com\.xunmeng\.pinduoduo"/);
  assert.ok(fs.existsSync('android-mvp/app/src/main/java/com/bianqujian/app/ParcelNotificationListener.kt'));
  const listener = fs.readFileSync('android-mvp/app/src/main/java/com/bianqujian/app/ParcelNotificationListener.kt', 'utf8');
  assert.match(listener, /已出库\|已取件\|已领取/);
  assert.match(listener, /com\.xunmeng\.pinduoduo/);
  assert.match(listener, /extractLocation/);
  assert.match(listener, /PICKED_UP/);
  assert.match(listener, /while \(fields\.size < 6\)/);
  assert.match(listener, /fields\[5\] = location/);
  const deploy = fs.readFileSync('android-mvp/install-restart.ps1', 'utf8');
  assert.match(deploy, /assembleDebug/);
  assert.match(deploy, /install -r/);
  assert.match(deploy, /force-stop com\.bianqujian\.app/);
  assert.match(deploy, /monkey -p com\.bianqujian\.app/);
  assert.match(code, /location: String/);
  assert.match(code, /未识别位置/);
});
